apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: cm9vdHBhc3N3b3Jk    # rootpassword in base64
  database: bXlkYg==                 # mydb in base64
  user: bXl1c2Vy                     # myuser in base64
  password: bXlwYXNzd29yZA==         # mypassword in base64