# --- 1. Definición de la StorageClass para el aprovisionamiento dinámico ---
# Minikube usa este provisioner para crear volúmenes hostPath de forma automática.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-storage-class
provisioner: k8s.io/minikube-hostpath
# La política "Retain" mantendrá el volumen y los datos incluso si el PVC es eliminado.
reclaimPolicy: Retain
volumeBindingMode: Immediate

---

# --- 2. Definición del PersistentVolumeClaim (la "solicitud" de almacenamiento) ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: mysql-storage-class

---

# --- 3. Definición del Deployment de MySQL ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "mydatabase"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc