apiVersion: v1
kind: Pod
metadata:
  name: mysql-temporal-pod
spec:
  containers:
  - name: mysql-temporal-container
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    - name: MYSQL_DATABASE
      value: "temp_db"
    ports:
    - containerPort: 3306