---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deepseek-ui-pvc
  namespace: deepseek
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepseek-ui
  namespace: deepseek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepseek-ui
  template:
    metadata:
      labels:
        app: deepseek-ui
    spec:
      containers:
        - name: deepseek-ui
          image: ghcr.io/ollama-webui/ollama-webui:latest
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          ports:
          - containerPort: 8080
          volumeMounts:
          - mountPath: /app/data
            name: data-storage
          env:
          - name: OLLAMA_API_BASE_URL
            value: "http://deepseek-server:11434/api"
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: deepseek-ui-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: deepseek-ui
  namespace: deepseek
spec:
  selector:
    app: deepseek-ui
  ports:
    - protocol: TCP
      port: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deepseek-ingress
  namespace: deepseek
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: running.deepseek.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: deepseek-ui
            port:
              number: 8080