apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: <your-account-id>.dkr.ecr.us-east-1.amazonaws.com/k8s-backend:v1
        ports:
        - containerPort: 5001
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: mysql
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: DB_PASSWORD
        resources:
          requests:
            cpu: "50m"
            memory: "256Mi"
          limits:
            cpu: "100m"
            memory: "512Mi"