apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  labels:
    type: local
    app: nginx-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/data
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  storageClassName: manual
  selector:
    matchLabels:
      type: local
      app: nginx-app
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
